---
- name: Create Headscale Systemd Unit File.
  ansible.builtin.template:
    src: headscale.service.j2
    dest: /etc/systemd/system/headscale.service
    owner: root
    group: root
    mode: 0644
  notify: enable service

- name: Set headscale config.yaml.
  ansible.builtin.copy:
    content: "{{ headscale_config | to_nice_yaml }}"
    dest: "{{ headscale_etc_dir_path }}/config.yaml"
    owner: "{{ headscale_user_name }}"
    group: "{{ headscale_user_name }}"
    mode: 0660
  notify: restart service

- name: Set headscale acl.yaml.
  ansible.builtin.copy:
    content: "{{ headscale_acl | to_nice_yaml }}"
    dest: "{{ headscale_etc_dir_path }}/acl.yaml"
    owner: "{{ headscale_user_name }}"
    group: "{{ headscale_user_name }}"
    mode: 0660
  notify: restart service

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
