---

- name: Set OS Architecture amd64.
  ansible.builtin.set_fact:
    os_architecture: 'amd64'
  when: ansible_architecture == 'x86_64'

- name: Set OS Architecture arm64.
  ansible.builtin.set_fact:
    os_architecture: 'arm64'
  when: ansible_architecture == 'aarch64'

- name: Set OS Architecture Others.
  ansible.builtin.set_fact:
    os_architecture: "{{ ansible_architecture }}"
  when: ansible_architecture != 'aarch64' and ansible_architecture != 'x86_64'

- name: Get Linux/Darwin.
  ansible.builtin.shell:
    cmd: |
      uname
  changed_when: false
  register: uname_result

# base releases url/version tag/filename
- name: Download headscale release for our architecture.
  ansible.builtin.get_url:
    url: "https://github.com/{{ headscale_github_repository }}/releases/download/\
          v{{ headscale_version }}/\
          headscale_{{ headscale_version }}_{{ uname_result.stdout }}_{{ os_architecture }}"
    dest: "{{ headscale_binary_path }}"
    owner: root
    group: root
    mode: 0755
    force:  true
  notify: restart service

- name: "Create group {{ headscale_user_name }}."
  ansible.builtin.group:
    name: "{{ headscale_user_name }}"
    gid: "{{ headscale_user_gid }}"
    state: present

- name: "Create user {{ headscale_user_name }}."
  ansible.builtin.user:
    name: "{{ headscale_user_name }}"
    uid: "{{ headscale_user_uid }}"
    group: "{{ headscale_user_name }}"
    system: true
    shell: /usr/bin/nologin
    home: "{{ headscale_lib_dir_path }}"
    state: present
    create_home: true

- name: "Create {{ headscale_lib_dir_path }} directory."
  ansible.builtin.file:
    path: "{{ headscale_lib_dir_path }}"
    state: directory
    owner: "{{ headscale_user_name }}"
    group: "{{ headscale_user_name }}"
    mode: 0770

- name: "Create {{ headscale_etc_dir_path }} directory."
  ansible.builtin.file:
    path: "{{ headscale_etc_dir_path }}"
    state: directory
    owner: "{{ headscale_user_name }}"
    group: "{{ headscale_user_name }}"
    mode: 0770

- name: "Create {{ headscale_run_dir_path }} directory."
  ansible.builtin.file:
    path: "{{ headscale_run_dir_path }}"
    state: directory
    owner: "{{ headscale_user_name }}"
    group: "{{ headscale_user_name }}"
    mode: 0770

- name: "Create {{ headscale_config.db_path }}."
  ansible.builtin.copy:
    dest: "{{ headscale_config.db_path }}"
    owner: "{{ headscale_user_name }}"
    group: "{{ headscale_user_name }}"
    content: ""
    mode: 0660
    force: false

- name: "Create {{ headscale_config.unix_socket }}."
  ansible.builtin.copy:
    dest: "{{ headscale_config.unix_socket | default('/var/run/headscale.sock') }}"
    owner: "{{ headscale_user_name }}"
    group: "{{ headscale_user_name }}"
    content: ""
    mode: "{{ headscale_config.unix_socket_permission | default('0770')}}"
    force: false