---

- name: Do version check.
  ansible.builtin.include_tasks:
    file: version-check.yml
  tags:
    - install
    - upgrade
    - configure
    - users

- name: Install headscale.
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - install
  when: not headscale_installed

- name: Upgrade headscale.
  ansible.builtin.include_tasks:
    file: upgrade.yml
  tags:
    - upgrade
  when: headscale_upgrade_required

- name: Configure headscale.
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - install
    - upgrade
    - configure

- name: Configure users.
  ansible.builtin.include_tasks:
    file: users.yml
  when: headscale_users is defined and headscale_users != 'None' and headscale_users != []
  tags:
    - install
    - users
