---

- name: Do version check.
  ansible.builtin.include_tasks:
    file: version-check.yml
  tags:
    - install
    - upgrade
    - configure
    - users

- name: Install headscale.
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - install
  when: not headscale_installed

- name: Upgrade headscale.
  ansible.builtin.include_tasks:
    file: upgrade.yml
  tags:
    - upgrade
  when: headscale_upgrade_required

- name: Configure headscale.
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - install
    - upgrade
    - configure

- name: Check that we can connect to headscale endpoint.
  ansible.builtin.uri:
    url: "{{ headscale_config.server_url | default('http://127.0.0.1:8080') }}"
    body_format: json
  register: headscale_endpoint
  until: headscale_endpoint.status == 200
  retries: 10

- name: Configure users.
  ansible.builtin.include_tasks:
    file: users.yml
  when: headscale_users is defined and headscale_users != 'None' and headscale_users != []
  tags:
    - install
    - users
