---

- name: Install headscale.
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - install

- name: Configure headscale.
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - install
    - configure

- name: Check that we can connect to the metrics endpoint.
  ansible.builtin.uri:
    url: "http://{{ headscale_metrics_listen_addr }}/metrics"
    body_format: json
  register: headscale_metrics
  until: headscale_metrics.status == 200
  retries: 10

- name: Configure namespaces.
  ansible.builtin.include_tasks:
    file: namespaces.yml
  when: headscale_namespaces is defined and headscale_namespaces != 'None'
  tags:
    - install
    - namespace
