---

- name: Do version check.
  ansible.builtin.include_tasks:
    file: version-check.yml
  tags:
    - install
    - upgrade
    - configure
    - namespace

- name: Install headscale.
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - install
  when: not headscale_installed

- name: Upgrade headscale.
  ansible.builtin.include_tasks:
    file: upgrade.yml
  tags:
    - upgrade
  when: headscale_upgrade_required

- name: Configure headscale.
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - install
    - upgrade
    - configure

- name: Check that we can connect to the metrics endpoint.
  ansible.builtin.uri:
    url: "http://{{ headscale_config.metrics_listen_addr | default('127.0.0.1:9090') }}/metrics"
    body_format: json
  register: headscale_metrics
  until: headscale_metrics.status == 200
  retries: 10

- name: Configure namespaces.
  ansible.builtin.include_tasks:
    file: namespaces.yml
  when: headscale_namespaces is defined and headscale_namespaces != 'None'
  tags:
    - install
    - namespace
