---
- name: Get Current Namespaces json.
  ansible.builtin.command:
    cmd: "{{ headscale_binary_path }} namespace list -o json-line"
  register: current_namespaces_json
  changed_when: false
  failed_when: current_namespaces_json.rc != 127 and current_namespaces_json.rc != 0

- name: Parse current namespace names.
  ansible.builtin.set_fact:
    current_namespaces: "{{ current_namespaces_json.stdout | from_json | json_query('[*].name') }}"
  when: current_namespaces_json.stdout != 'null'

- name: Set already existing namespaces.
  ansible.builtin.set_fact:
    existing_namespaces: "{{ headscale_namespaces | intersect(current_namespaces) }}"
  when: current_namespaces is defined

- name: Set namespaces to remove.
  ansible.builtin.set_fact:
    namespaces_to_remove: "{{ current_namespaces | difference(existing_namespaces) }}"
  when: existing_namespaces is defined and existing_namespaces != 'None' and headscale_remove_unmanaged_namespaces

- name: Ensure no namepaces exist except the ones we've defined.
  ansible.builtin.command:
    cmd: "{{ headscale_binary_path }} namespace destroy --force '{{ item }}'"
  with_items: "{{ namespaces_to_remove }}"
  when: namespaces_to_remove is defined and namespaces_to_remove != 'None' and headscale_remove_unmanaged_namespaces

- name: Set namespaces_to_create if existing_namespaces is defined.
  ansible.builtin.set_fact:
    namespaces_to_create: "{{ headscale_namespaces | difference(existing_namespaces) }}"
  when: existing_namespaces is defined and existing_namespaces != headscale_namespaces

- name: Set namespaces_to_create if existing_namespaces is not defined.
  ansible.builtin.set_fact:
    namespaces_to_create: "{{ headscale_namespaces }}"
  when: existing_namespaces is not defined

- name: Create missing namespaces.
  ansible.builtin.command:
    cmd: "{{ headscale_binary_path }} namespaces create {{ item }}"
  with_items: "{{ namespaces_to_create }}"
  register: namespace_created
  changed_when: "'Namespace created' in namespace_created.stdout"
  when: namespaces_to_create is defined and namespaces_to_create != 'None'
