---
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable service
  ansible.builtin.systemd:
    name: headscale.service
    state: started
    enabled: true

- name: restart service
  ansible.builtin.systemd:
    name: headscale.service
    state: restarted
