---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
# cgroupns_mode: host
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:rw
#      - /var/lib/containerd
# are required to test systemd related tasks
# since docker switched to cgroups v2.
# https://www.jeffgeerling.com/blog/2022/docker-and-systemd-getting-rid-dreaded-failed-connect-bus-error
  - name: centos8
    image: "geerlingguy/docker-centos8-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host

  - name: debian10
    image: "geerlingguy/docker-debian10-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host

  - name: debian11
    image: "geerlingguy/docker-debian11-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host

  - name: ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host

  - name: ubuntu2204
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
